services:
  app:
    container_name: ${APP_NAME}-app
    image: php:8.4.16-fpm-bookworm
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - default

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
    networks:
      - default

  db:
    container_name: ${APP_NAME}-db
    image: postgres:15.15
    ports:
      - 5432:5432
    volumes:
      - saas_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    networks:
      - default

volumes:
  saas_db:


networks:
  default:
    name: lcas_network
    driver: bridge
